create table "public"."cash_desks" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "balance" numeric not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."cash_desks" enable row level security;

create table "public"."debtors" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "amount" numeric not null,
    "due_date" date not null,
    "status" text not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."debtors" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone default now(),
    "full_name" text,
    "avatar_url" text,
    "role_id" bigint,
    "created_at" timestamp with time zone default now()
);


alter table "public"."profiles" enable row level security;

create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" text default 'admin'::text,
    "scope" text[] default '{}'::text[]
);


alter table "public"."roles" enable row level security;

create table "public"."user_action_logs" (
    "id" bigint generated by default as identity not null,
    "timestamp" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "action" character varying not null,
    "entity" character varying not null,
    "entity_id" character varying,
    "details" jsonb
);


alter table "public"."user_action_logs" enable row level security;

CREATE UNIQUE INDEX cash_desks_pkey ON public.cash_desks USING btree (id);

CREATE UNIQUE INDEX debtors_pkey ON public.debtors USING btree (id);

CREATE INDEX idx_user_action_logs_timestamp ON public.user_action_logs USING btree ("timestamp");

CREATE INDEX idx_user_action_logs_user_id ON public.user_action_logs USING btree (user_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX roles_role_key ON public.roles USING btree (role);

CREATE UNIQUE INDEX user_action_logs_pkey ON public.user_action_logs USING btree (id);

alter table "public"."cash_desks" add constraint "cash_desks_pkey" PRIMARY KEY using index "cash_desks_pkey";

alter table "public"."debtors" add constraint "debtors_pkey" PRIMARY KEY using index "debtors_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."user_action_logs" add constraint "user_action_logs_pkey" PRIMARY KEY using index "user_action_logs_pkey";

alter table "public"."debtors" add constraint "debtors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."debtors" validate constraint "debtors_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_role_id_fkey";

alter table "public"."roles" add constraint "roles_role_key" UNIQUE using index "roles_role_key";

alter table "public"."user_action_logs" add constraint "user_action_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_action_logs" validate constraint "user_action_logs_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.clean_old_logs()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM public.user_action_logs
  WHERE timestamp < NOW() - INTERVAL '3 months';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.log_user_action()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF (TG_OP = 'DELETE') THEN
    INSERT INTO public.user_action_logs (
      user_id, action, entity, entity_id, details
    )
    VALUES (
      OLD.id, TG_OP, TG_TABLE_NAME, OLD.id::text, row_to_json(OLD)::jsonb
    );
  ELSE
    INSERT INTO public.user_action_logs (
      user_id, action, entity, entity_id, details
    )
    VALUES (
      NEW.id, TG_OP, TG_TABLE_NAME, NEW.id::text, row_to_json(NEW)::jsonb
    );
  END IF;

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."cash_desks" to "anon";

grant insert on table "public"."cash_desks" to "anon";

grant references on table "public"."cash_desks" to "anon";

grant select on table "public"."cash_desks" to "anon";

grant trigger on table "public"."cash_desks" to "anon";

grant truncate on table "public"."cash_desks" to "anon";

grant update on table "public"."cash_desks" to "anon";

grant delete on table "public"."cash_desks" to "authenticated";

grant insert on table "public"."cash_desks" to "authenticated";

grant references on table "public"."cash_desks" to "authenticated";

grant select on table "public"."cash_desks" to "authenticated";

grant trigger on table "public"."cash_desks" to "authenticated";

grant truncate on table "public"."cash_desks" to "authenticated";

grant update on table "public"."cash_desks" to "authenticated";

grant delete on table "public"."cash_desks" to "service_role";

grant insert on table "public"."cash_desks" to "service_role";

grant references on table "public"."cash_desks" to "service_role";

grant select on table "public"."cash_desks" to "service_role";

grant trigger on table "public"."cash_desks" to "service_role";

grant truncate on table "public"."cash_desks" to "service_role";

grant update on table "public"."cash_desks" to "service_role";

grant delete on table "public"."debtors" to "anon";

grant insert on table "public"."debtors" to "anon";

grant references on table "public"."debtors" to "anon";

grant select on table "public"."debtors" to "anon";

grant trigger on table "public"."debtors" to "anon";

grant truncate on table "public"."debtors" to "anon";

grant update on table "public"."debtors" to "anon";

grant delete on table "public"."debtors" to "authenticated";

grant insert on table "public"."debtors" to "authenticated";

grant references on table "public"."debtors" to "authenticated";

grant select on table "public"."debtors" to "authenticated";

grant trigger on table "public"."debtors" to "authenticated";

grant truncate on table "public"."debtors" to "authenticated";

grant update on table "public"."debtors" to "authenticated";

grant delete on table "public"."debtors" to "service_role";

grant insert on table "public"."debtors" to "service_role";

grant references on table "public"."debtors" to "service_role";

grant select on table "public"."debtors" to "service_role";

grant trigger on table "public"."debtors" to "service_role";

grant truncate on table "public"."debtors" to "service_role";

grant update on table "public"."debtors" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."user_action_logs" to "anon";

grant insert on table "public"."user_action_logs" to "anon";

grant references on table "public"."user_action_logs" to "anon";

grant select on table "public"."user_action_logs" to "anon";

grant trigger on table "public"."user_action_logs" to "anon";

grant truncate on table "public"."user_action_logs" to "anon";

grant update on table "public"."user_action_logs" to "anon";

grant delete on table "public"."user_action_logs" to "authenticated";

grant insert on table "public"."user_action_logs" to "authenticated";

grant references on table "public"."user_action_logs" to "authenticated";

grant select on table "public"."user_action_logs" to "authenticated";

grant trigger on table "public"."user_action_logs" to "authenticated";

grant truncate on table "public"."user_action_logs" to "authenticated";

grant update on table "public"."user_action_logs" to "authenticated";

grant delete on table "public"."user_action_logs" to "service_role";

grant insert on table "public"."user_action_logs" to "service_role";

grant references on table "public"."user_action_logs" to "service_role";

grant select on table "public"."user_action_logs" to "service_role";

grant trigger on table "public"."user_action_logs" to "service_role";

grant truncate on table "public"."user_action_logs" to "service_role";

grant update on table "public"."user_action_logs" to "service_role";

create policy "Allow admin to delete"
on "public"."profiles"
as permissive
for delete
to public
using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role_id = 1)))));


create policy "Allow profile creation for users with users scope"
on "public"."profiles"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM (roles
     JOIN profiles profiles_1 ON ((profiles_1.role_id = roles.id)))
  WHERE ((profiles_1.id = auth.uid()) AND ('users'::text = ANY (roles.scope))))));


create policy "Public profiles are viewable by everyone."
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Users can update own profile."
on "public"."profiles"
as permissive
for update
to public
using ((auth.uid() = id));


create policy "Allow authenticated read access"
on "public"."roles"
as permissive
for select
to public
using ((auth.uid() IS NOT NULL));


create policy "Allow admin to delete"
on "public"."user_action_logs"
as permissive
for delete
to public
using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role_id = 1)))));


create policy "Allow authenticated users to insert"
on "public"."user_action_logs"
as permissive
for insert
to public
with check ((auth.role() = 'authenticated'::text));


create policy "Allow authenticated users to select"
on "public"."user_action_logs"
as permissive
for select
to public
using ((auth.role() = 'authenticated'::text));


CREATE TRIGGER cash_desk_action_log AFTER INSERT OR DELETE OR UPDATE ON public.cash_desks FOR EACH ROW EXECUTE FUNCTION log_user_action();

CREATE TRIGGER debtor_action_log AFTER INSERT OR DELETE OR UPDATE ON public.debtors FOR EACH ROW EXECUTE FUNCTION log_user_action();

CREATE TRIGGER profile_action_log AFTER INSERT OR DELETE OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION log_user_action();
