create type "public"."session_language" as enum ('en', 'de', 'it', 'fr');

create type "public"."session_status" as enum ('open', 'changed', 'accepted', 'cancelled', 'finished', 'doctor_missed', 'pet_owner_missed');

create type "public"."user_role" as enum ('customer', 'doctor', 'admin');

create table "public"."call_sessions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "pet_owner_id" uuid not null,
    "doctor_id" uuid,
    "pet_id" uuid not null,
    "start_time" timestamp with time zone not null,
    "description" text not null,
    "language" session_language not null,
    "started_at" timestamp with time zone,
    "finished_at" timestamp with time zone,
    "cancelled_at" timestamp with time zone,
    "status" session_status not null default 'open'::session_status,
    "changed_start_time" timestamp with time zone
);


alter table "public"."call_sessions" enable row level security;

create table "public"."doctors" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" uuid not null
);


alter table "public"."doctors" enable row level security;

create table "public"."pet_owners" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" uuid not null
);


alter table "public"."pet_owners" enable row level security;

create table "public"."pets" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "name" text not null,
    "owner_id" uuid not null,
    "species" text not null,
    "breed" text,
    "birth_date" timestamp with time zone
);


alter table "public"."pets" enable row level security;

create table "public"."user_action" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" text not null,
    "metadata" jsonb,
    "user_id" uuid not null,
    "doctor_id" uuid,
    "pet_owner_id" uuid,
    "call_session_id" uuid
);


alter table "public"."user_action" enable row level security;

CREATE UNIQUE INDEX doctor_pkey ON public.doctors USING btree (id);

CREATE UNIQUE INDEX doctor_user_id_key ON public.doctors USING btree (user_id);

CREATE UNIQUE INDEX pet_owner_pkey ON public.pet_owners USING btree (id);

CREATE UNIQUE INDEX pet_owner_user_id_key ON public.pet_owners USING btree (user_id);

CREATE UNIQUE INDEX pet_pkey ON public.pets USING btree (id);

CREATE UNIQUE INDEX session_pkey ON public.call_sessions USING btree (id);

CREATE UNIQUE INDEX user_action_pkey ON public.user_action USING btree (id);

alter table "public"."call_sessions" add constraint "session_pkey" PRIMARY KEY using index "session_pkey";

alter table "public"."doctors" add constraint "doctor_pkey" PRIMARY KEY using index "doctor_pkey";

alter table "public"."pet_owners" add constraint "pet_owner_pkey" PRIMARY KEY using index "pet_owner_pkey";

alter table "public"."pets" add constraint "pet_pkey" PRIMARY KEY using index "pet_pkey";

alter table "public"."user_action" add constraint "user_action_pkey" PRIMARY KEY using index "user_action_pkey";

alter table "public"."call_sessions" add constraint "call_sessions_doctor_id_fkey1" FOREIGN KEY (doctor_id) REFERENCES doctors(id) not valid;

alter table "public"."call_sessions" validate constraint "call_sessions_doctor_id_fkey1";

alter table "public"."call_sessions" add constraint "call_sessions_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES pets(id) not valid;

alter table "public"."call_sessions" validate constraint "call_sessions_pet_id_fkey";

alter table "public"."call_sessions" add constraint "call_sessions_pet_owner_id_fkey" FOREIGN KEY (pet_owner_id) REFERENCES pet_owners(id) not valid;

alter table "public"."call_sessions" validate constraint "call_sessions_pet_owner_id_fkey";

alter table "public"."doctors" add constraint "doctor_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."doctors" validate constraint "doctor_user_id_fkey";

alter table "public"."doctors" add constraint "doctor_user_id_key" UNIQUE using index "doctor_user_id_key";

alter table "public"."pet_owners" add constraint "pet_owner_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."pet_owners" validate constraint "pet_owner_user_id_fkey";

alter table "public"."pet_owners" add constraint "pet_owner_user_id_key" UNIQUE using index "pet_owner_user_id_key";

alter table "public"."pets" add constraint "pets_owner_id_fkey1" FOREIGN KEY (owner_id) REFERENCES pet_owners(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."pets" validate constraint "pets_owner_id_fkey1";

alter table "public"."user_action" add constraint "user_action_call_session_id_fkey" FOREIGN KEY (call_session_id) REFERENCES call_sessions(id) not valid;

alter table "public"."user_action" validate constraint "user_action_call_session_id_fkey";

alter table "public"."user_action" add constraint "user_action_doctor_id_fkey" FOREIGN KEY (doctor_id) REFERENCES doctors(id) not valid;

alter table "public"."user_action" validate constraint "user_action_doctor_id_fkey";

alter table "public"."user_action" add constraint "user_action_pet_owner_id_fkey" FOREIGN KEY (pet_owner_id) REFERENCES pet_owners(id) not valid;

alter table "public"."user_action" validate constraint "user_action_pet_owner_id_fkey";

alter table "public"."user_action" add constraint "user_action_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."user_action" validate constraint "user_action_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_call_session("petId" uuid, "startTime" timestamp with time zone, "languageCode" session_language, "sessionDescription" text)
 RETURNS call_sessions
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  "currentUserId" uuid;
  "currentOwnerId" uuid;
  result public.call_sessions;
begin
  -- Get the authenticated user's ID
  "currentUserId" := auth.uid();

  if "currentUserId" is null then
    raise exception 'Unauthorized: No user ID found';
  end if;

  -- Find matching pet_owner
  select id into "currentOwnerId"
  from public.pet_owners
  where user_id = "currentUserId";

  if "currentOwnerId" is null then
    raise exception 'Unauthorized: No matching pet owner found';
  end if;

  -- Ensure the pet belongs to this owner
  if not exists (
    select 1
    from public.pets
    where id = "petId" and owner_id = "currentOwnerId"
  ) then
    raise exception 'Unauthorized: Pet does not belong to the user';
  end if;

  -- Insert call session and capture the result
  insert into public.call_sessions (
    pet_id, pet_owner_id, start_time, language, description, created_at
  )
  values (
    "petId", "currentOwnerId", "startTime", "languageCode", "sessionDescription", now()
  )
  returning * into result;

  return result;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.debug_uid()
 RETURNS uuid
 LANGUAGE sql
AS $function$
  SELECT auth.uid();
$function$
;

grant delete on table "public"."call_sessions" to "anon";

grant insert on table "public"."call_sessions" to "anon";

grant references on table "public"."call_sessions" to "anon";

grant select on table "public"."call_sessions" to "anon";

grant trigger on table "public"."call_sessions" to "anon";

grant truncate on table "public"."call_sessions" to "anon";

grant update on table "public"."call_sessions" to "anon";

grant delete on table "public"."call_sessions" to "authenticated";

grant insert on table "public"."call_sessions" to "authenticated";

grant references on table "public"."call_sessions" to "authenticated";

grant select on table "public"."call_sessions" to "authenticated";

grant trigger on table "public"."call_sessions" to "authenticated";

grant truncate on table "public"."call_sessions" to "authenticated";

grant update on table "public"."call_sessions" to "authenticated";

grant delete on table "public"."call_sessions" to "service_role";

grant insert on table "public"."call_sessions" to "service_role";

grant references on table "public"."call_sessions" to "service_role";

grant select on table "public"."call_sessions" to "service_role";

grant trigger on table "public"."call_sessions" to "service_role";

grant truncate on table "public"."call_sessions" to "service_role";

grant update on table "public"."call_sessions" to "service_role";

grant delete on table "public"."doctors" to "anon";

grant insert on table "public"."doctors" to "anon";

grant references on table "public"."doctors" to "anon";

grant select on table "public"."doctors" to "anon";

grant trigger on table "public"."doctors" to "anon";

grant truncate on table "public"."doctors" to "anon";

grant update on table "public"."doctors" to "anon";

grant delete on table "public"."doctors" to "authenticated";

grant insert on table "public"."doctors" to "authenticated";

grant references on table "public"."doctors" to "authenticated";

grant select on table "public"."doctors" to "authenticated";

grant trigger on table "public"."doctors" to "authenticated";

grant truncate on table "public"."doctors" to "authenticated";

grant update on table "public"."doctors" to "authenticated";

grant delete on table "public"."doctors" to "service_role";

grant insert on table "public"."doctors" to "service_role";

grant references on table "public"."doctors" to "service_role";

grant select on table "public"."doctors" to "service_role";

grant trigger on table "public"."doctors" to "service_role";

grant truncate on table "public"."doctors" to "service_role";

grant update on table "public"."doctors" to "service_role";

grant delete on table "public"."pet_owners" to "anon";

grant insert on table "public"."pet_owners" to "anon";

grant references on table "public"."pet_owners" to "anon";

grant select on table "public"."pet_owners" to "anon";

grant trigger on table "public"."pet_owners" to "anon";

grant truncate on table "public"."pet_owners" to "anon";

grant update on table "public"."pet_owners" to "anon";

grant delete on table "public"."pet_owners" to "authenticated";

grant insert on table "public"."pet_owners" to "authenticated";

grant references on table "public"."pet_owners" to "authenticated";

grant select on table "public"."pet_owners" to "authenticated";

grant trigger on table "public"."pet_owners" to "authenticated";

grant truncate on table "public"."pet_owners" to "authenticated";

grant update on table "public"."pet_owners" to "authenticated";

grant delete on table "public"."pet_owners" to "service_role";

grant insert on table "public"."pet_owners" to "service_role";

grant references on table "public"."pet_owners" to "service_role";

grant select on table "public"."pet_owners" to "service_role";

grant trigger on table "public"."pet_owners" to "service_role";

grant truncate on table "public"."pet_owners" to "service_role";

grant update on table "public"."pet_owners" to "service_role";

grant delete on table "public"."pets" to "anon";

grant insert on table "public"."pets" to "anon";

grant references on table "public"."pets" to "anon";

grant select on table "public"."pets" to "anon";

grant trigger on table "public"."pets" to "anon";

grant truncate on table "public"."pets" to "anon";

grant update on table "public"."pets" to "anon";

grant delete on table "public"."pets" to "authenticated";

grant insert on table "public"."pets" to "authenticated";

grant references on table "public"."pets" to "authenticated";

grant select on table "public"."pets" to "authenticated";

grant trigger on table "public"."pets" to "authenticated";

grant truncate on table "public"."pets" to "authenticated";

grant update on table "public"."pets" to "authenticated";

grant delete on table "public"."pets" to "service_role";

grant insert on table "public"."pets" to "service_role";

grant references on table "public"."pets" to "service_role";

grant select on table "public"."pets" to "service_role";

grant trigger on table "public"."pets" to "service_role";

grant truncate on table "public"."pets" to "service_role";

grant update on table "public"."pets" to "service_role";

grant delete on table "public"."user_action" to "anon";

grant insert on table "public"."user_action" to "anon";

grant references on table "public"."user_action" to "anon";

grant select on table "public"."user_action" to "anon";

grant trigger on table "public"."user_action" to "anon";

grant truncate on table "public"."user_action" to "anon";

grant update on table "public"."user_action" to "anon";

grant delete on table "public"."user_action" to "authenticated";

grant insert on table "public"."user_action" to "authenticated";

grant references on table "public"."user_action" to "authenticated";

grant select on table "public"."user_action" to "authenticated";

grant trigger on table "public"."user_action" to "authenticated";

grant truncate on table "public"."user_action" to "authenticated";

grant update on table "public"."user_action" to "authenticated";

grant delete on table "public"."user_action" to "service_role";

grant insert on table "public"."user_action" to "service_role";

grant references on table "public"."user_action" to "service_role";

grant select on table "public"."user_action" to "service_role";

grant trigger on table "public"."user_action" to "service_role";

grant truncate on table "public"."user_action" to "service_role";

grant update on table "public"."user_action" to "service_role";

create policy "Allow doctors to select sessions with no doctor assigned"
on "public"."call_sessions"
as permissive
for select
to public
using ((doctor_id IS NULL));


create policy "Allow doctors to select their own call sessions"
on "public"."call_sessions"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM doctors
  WHERE ((doctors.id = call_sessions.doctor_id) AND (doctors.user_id = auth.uid())))));


create policy "Allow pet owners to select their call sessions"
on "public"."call_sessions"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM pet_owners
  WHERE ((pet_owners.id = call_sessions.pet_owner_id) AND (pet_owners.user_id = auth.uid())))));


create policy "Allow select for own doctor record"
on "public"."doctors"
as permissive
for select
to public
using ((user_id = auth.uid()));


create policy "Allow update for own doctor record"
on "public"."doctors"
as permissive
for update
to public
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));


create policy "Allow select for own pet_owner record"
on "public"."pet_owners"
as permissive
for select
to public
using ((user_id = auth.uid()));


create policy "Allow update for own pet_owner record"
on "public"."pet_owners"
as permissive
for update
to public
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));


create policy "Allow owners to select their pets"
on "public"."pets"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM pet_owners
  WHERE ((pet_owners.id = pets.owner_id) AND (pet_owners.user_id = auth.uid())))));


create policy "Allow owners to update their pets"
on "public"."pets"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM pet_owners
  WHERE ((pet_owners.id = pets.owner_id) AND (pet_owners.user_id = auth.uid())))));



